namespace MvvmApp.GeneratorsOld;

public static class SourceHelper
{

  public const string AttributeNamespace = "Prism.Avalonia.Toolkit";

  public const string NotifyFieldAttribute = "NotifyFieldAttribute";

  public const string NotifyFieldAttributeClass = $@"
// <auto-generated />
using System;
namespace {AttributeNamespace}
{{
    [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    [System.Diagnostics.Conditional(""NotifyFieldGenerator_DEBUG"")]
    sealed class {NotifyFieldAttribute} : Attribute
    {{
        public {NotifyFieldAttribute}()
        {{
        }}

        public string PropertyName {{ get; set; }}
    }}
}}
";

  public const string NotifyFieldAttributeFullNamespace = $"{AttributeNamespace}.{NotifyFieldAttribute}";

  public const string NotifyPropertyChangedNamespace = "System.ComponentModel.INotifyPropertyChanged";

}
