namespace MvvmApp.Generators;

public static class SourceHelper
{
  public const string NamespaceNotifyField = $"{NamespaceRoot}.{NotifyFieldAttribute}";

  public const string NamespaceRoot = "Prism.Avalonia.Toolkit";

  public const string NotifyFieldAttribute = "NotifyFieldAttribute";

  public const string NotifyFieldAttributeClass = $@"
// <auto-generated />
using System;
namespace {NamespaceRoot}
{{
    [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    [System.Diagnostics.Conditional(""NotifyFieldGenerator_DEBUG"")]
    sealed class {NotifyFieldAttribute} : Attribute
    {{
        public {NotifyFieldAttribute}()
        {{
        }}

        public string PropertyName {{ get; set; }}
    }}
}}
";

  public const string NotifyPropertyChanged = "System.ComponentModel.INotifyPropertyChanged";
}
